[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Collect the stars!"
requires-python = ">=3.14"
dependencies = [
    "advent-of-code-data==2.1",
    "portion==2.6.1",
    "pytest==9.0.1",
    "ruff==0.14.7",
    "networkx==3.6",
    "shapely>=2.1.2",
]

[tool.ruff]
line-length = 120
