name: Python Tests

on:
  push:
    branches: [ "primary" ]
  pull_request:
    branches: [ "primary" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - uses: astral-sh/setup-uv@v1
    - name: Run tests
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}
      run: |
        uv run pytest
